export const data = JSON.parse("{\"key\":\"v-0f5bcbd0\",\"path\":\"/%E5%BC%80%E5%8F%91/%E3%80%8ESwiftUI%E3%80%8F/1.html\",\"title\":\"01.概述\",\"lang\":\"zh-CN\",\"frontmatter\":{\"date\":\"2022-5-06\",\"category\":[\"iOS\",\"Swift\",\"SwiftUI\"],\"description\":\"01.概述 SwiftUI 是苹果公司推出的一款全新的 UI 开发框架，旨在为开发者提供更加现代化、易于使用的界面设计工具，以及更加高效和简洁的代码编写方式。 SwiftUI 引入了一系列新的语法和组件，使得开发者可以更加轻松地构建复杂的用户界面，同时也大大提升了应用程序的性能和交互体验。 SwiftUI 的主要特点如下： 声明式语法 SwiftUI 采用了声明式语法，使得开发者可以更加方便地描述应用程序的用户界面。开发者只需要定义所需的组件和布局方式，而不必关心具体的实现细节。相比传统的命令式编程方式，声明式语法更加简洁、易于维护和扩展。 声明式语法创建一个简单的按钮：\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"http://yunpu.tech/%E5%BC%80%E5%8F%91/%E3%80%8ESwiftUI%E3%80%8F/1.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"夏日的瓜牛\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"01.概述\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"01.概述 SwiftUI 是苹果公司推出的一款全新的 UI 开发框架，旨在为开发者提供更加现代化、易于使用的界面设计工具，以及更加高效和简洁的代码编写方式。 SwiftUI 引入了一系列新的语法和组件，使得开发者可以更加轻松地构建复杂的用户界面，同时也大大提升了应用程序的性能和交互体验。 SwiftUI 的主要特点如下： 声明式语法 SwiftUI 采用了声明式语法，使得开发者可以更加方便地描述应用程序的用户界面。开发者只需要定义所需的组件和布局方式，而不必关心具体的实现细节。相比传统的命令式编程方式，声明式语法更加简洁、易于维护和扩展。 声明式语法创建一个简单的按钮：\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2022-05-05T16:00:00.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"01.概述\\\",\\\"image\\\":[\\\"\\\"],\\\"datePublished\\\":\\\"2022-05-05T16:00:00.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[]}\"]]},\"headers\":[{\"level\":2,\"title\":\"声明式语法\",\"slug\":\"声明式语法\",\"link\":\"#声明式语法\",\"children\":[]},{\"level\":2,\"title\":\"自动化布局\",\"slug\":\"自动化布局\",\"link\":\"#自动化布局\",\"children\":[]},{\"level\":2,\"title\":\"数据驱动界面\",\"slug\":\"数据驱动界面\",\"link\":\"#数据驱动界面\",\"children\":[]},{\"level\":2,\"title\":\"可组合性\",\"slug\":\"可组合性\",\"link\":\"#可组合性\",\"children\":[]},{\"level\":2,\"title\":\"实时预览\",\"slug\":\"实时预览\",\"link\":\"#实时预览\",\"children\":[]},{\"level\":2,\"title\":\"总结\",\"slug\":\"总结\",\"link\":\"#总结\",\"children\":[]}],\"readingTime\":{\"minutes\":3.17,\"words\":951},\"filePathRelative\":\"开发/『SwiftUI』/1.md\",\"localizedDate\":\"2022年5月6日\",\"excerpt\":\"<h1> 01.概述</h1>\\n<p>SwiftUI 是苹果公司推出的一款全新的 UI 开发框架，旨在为开发者提供更加现代化、易于使用的界面设计工具，以及更加高效和简洁的代码编写方式。<br>\\nSwiftUI 引入了一系列新的语法和组件，使得开发者可以更加轻松地构建复杂的用户界面，同时也大大提升了应用程序的性能和交互体验。<br>\\nSwiftUI 的主要特点如下：</p>\\n<h2> 声明式语法</h2>\\n<p>SwiftUI 采用了声明式语法，使得开发者可以更加方便地描述应用程序的用户界面。开发者只需要定义所需的组件和布局方式，而不必关心具体的实现细节。相比传统的命令式编程方式，声明式语法更加简洁、易于维护和扩展。<br>\\n声明式语法创建一个简单的按钮：</p>\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
