export const data = JSON.parse("{\"key\":\"v-9f72564c\",\"path\":\"/%E5%BD%92%E6%A1%A3/Xcode/5%E7%9A%84%E5%89%AF%E6%9C%AC.html\",\"title\":\"LLDB 调试\",\"lang\":\"zh-CN\",\"frontmatter\":{\"date\":\"2022-04-01T00:00:00.000Z\",\"category\":[\"苹果\"],\"tag\":[\"红\",\"大\",\"圆\"],\"description\":\"LLDB 调试 原生 LLDB 命令 p 打印基本数据类型的值，查看对象返回对象的指针地址。 po 打印对象的描述，常量、变量、表达式返回的对象等。 pclass 打印对象继承关系 presponder 打印响应链 bt 打印线程的堆栈信息（bt all 打印全部线程堆栈信息）。 e 动态变量赋值： if 处断点，控制台输入 e dataArray.count = 0 回车，继续运行即可：\"},\"headers\":[{\"level\":2,\"title\":\"原生 LLDB 命令\",\"slug\":\"原生-lldb-命令\",\"link\":\"#原生-lldb-命令\",\"children\":[{\"level\":3,\"title\":\"p\",\"slug\":\"p\",\"link\":\"#p\",\"children\":[]},{\"level\":3,\"title\":\"bt\",\"slug\":\"bt\",\"link\":\"#bt\",\"children\":[]},{\"level\":3,\"title\":\"e\",\"slug\":\"e\",\"link\":\"#e\",\"children\":[]},{\"level\":3,\"title\":\"call\",\"slug\":\"call\",\"link\":\"#call\",\"children\":[]},{\"level\":3,\"title\":\"image\",\"slug\":\"image\",\"link\":\"#image\",\"children\":[]},{\"level\":3,\"title\":\"breakpoint\",\"slug\":\"breakpoint\",\"link\":\"#breakpoint\",\"children\":[]},{\"level\":3,\"title\":\"command alias\",\"slug\":\"command-alias\",\"link\":\"#command-alias\",\"children\":[]},{\"level\":3,\"title\":\"command alias %1 %2\",\"slug\":\"command-alias-1-2\",\"link\":\"#command-alias-1-2\",\"children\":[]},{\"level\":3,\"title\":\"menthods\",\"slug\":\"menthods\",\"link\":\"#menthods\",\"children\":[]},{\"level\":3,\"title\":\"pachtion\",\"slug\":\"pachtion\",\"link\":\"#pachtion\",\"children\":[]},{\"level\":3,\"title\":\"search\",\"slug\":\"search\",\"link\":\"#search\",\"children\":[]},{\"level\":3,\"title\":\"所有 LLDB 命令\",\"slug\":\"所有-lldb-命令\",\"link\":\"#所有-lldb-命令\",\"children\":[]}]},{\"level\":2,\"title\":\"插件\",\"slug\":\"插件\",\"link\":\"#插件\",\"children\":[{\"level\":3,\"title\":\"Chisel\",\"slug\":\"chisel\",\"link\":\"#chisel\",\"children\":[]},{\"level\":3,\"title\":\"LLDB\",\"slug\":\"lldb\",\"link\":\"#lldb\",\"children\":[]}]},{\"level\":2,\"title\":\"自定义插件\",\"slug\":\"自定义插件\",\"link\":\"#自定义插件\",\"children\":[]}],\"readingTime\":{\"minutes\":13.28,\"words\":3985},\"filePathRelative\":\"归档/Xcode/5的副本.md\",\"localizedDate\":\"2022年4月1日\",\"excerpt\":\"<h1> LLDB 调试</h1>\\n<h2> 原生 LLDB 命令</h2>\\n<h3> p</h3>\\n<p>打印基本数据类型的值，查看对象返回对象的指针地址。</p>\\n<h4> po</h4>\\n<p>打印对象的描述，常量、变量、表达式返回的对象等。</p>\\n<h4> pclass</h4>\\n<p>打印对象继承关系</p>\\n<h4> presponder</h4>\\n<p>打印响应链</p>\\n<h3> bt</h3>\\n<p>打印线程的堆栈信息（bt all 打印全部线程堆栈信息）。</p>\\n<h3> e</h3>\\n<p>动态变量赋值：<br>\\nif 处断点，控制台输入 e dataArray.count = 0 回车，继续运行即可：</p>\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
