export const data = JSON.parse("{\"key\":\"v-581a7c20\",\"path\":\"/%E5%85%B6%E4%BB%96/SwiftUI/11.html\",\"title\":\"11.容器视图\",\"lang\":\"zh-CN\",\"frontmatter\":{\"date\":\"2022-01-04T00:00:00.000Z\",\"category\":[\"苹果\",\"水果\"],\"tag\":[\"红\",\"大\",\"圆\"],\"description\":\"11.容器视图 容器视图是 SwiftUI 中的一个重要组成部分，它们用于组合和管理其他视图，从而创建出复杂的用户界面。 常见的容器视图 SwiftUI 中有很多种容器视图，每种容器视图都有不同的用途和特点。下面是一些常见的容器视图： VStack 和 HStack VStack 和 HStack 都用于将多个视图按垂直或水平方向排列。VStack 将视图从上到下排列，而 HStack 将视图从左到右排列。这两种容器视图都支持对子视图的对齐方式、间距、填充等样式的设置。 ZStack\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"http://yunpu.tech/%E5%85%B6%E4%BB%96/SwiftUI/11.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"夏日的瓜牛\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"11.容器视图\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"11.容器视图 容器视图是 SwiftUI 中的一个重要组成部分，它们用于组合和管理其他视图，从而创建出复杂的用户界面。 常见的容器视图 SwiftUI 中有很多种容器视图，每种容器视图都有不同的用途和特点。下面是一些常见的容器视图： VStack 和 HStack VStack 和 HStack 都用于将多个视图按垂直或水平方向排列。VStack 将视图从上到下排列，而 HStack 将视图从左到右排列。这两种容器视图都支持对子视图的对齐方式、间距、填充等样式的设置。 ZStack\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"红\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"大\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"圆\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2022-01-04T00:00:00.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"11.容器视图\\\",\\\"image\\\":[\\\"\\\"],\\\"datePublished\\\":\\\"2022-01-04T00:00:00.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[]}\"]]},\"headers\":[{\"level\":2,\"title\":\"常见的容器视图\",\"slug\":\"常见的容器视图\",\"link\":\"#常见的容器视图\",\"children\":[{\"level\":3,\"title\":\"VStack 和 HStack\",\"slug\":\"vstack-和-hstack\",\"link\":\"#vstack-和-hstack\",\"children\":[]},{\"level\":3,\"title\":\"ZStack\",\"slug\":\"zstack\",\"link\":\"#zstack\",\"children\":[]},{\"level\":3,\"title\":\"ScrollView\",\"slug\":\"scrollview\",\"link\":\"#scrollview\",\"children\":[]},{\"level\":3,\"title\":\"List\",\"slug\":\"list\",\"link\":\"#list\",\"children\":[]},{\"level\":3,\"title\":\"Form\",\"slug\":\"form\",\"link\":\"#form\",\"children\":[]}]},{\"level\":2,\"title\":\"如何使用容器视图\",\"slug\":\"如何使用容器视图\",\"link\":\"#如何使用容器视图\",\"children\":[]}],\"readingTime\":{\"minutes\":1.81,\"words\":544},\"filePathRelative\":\"其他/SwiftUI/11.md\",\"localizedDate\":\"2022年1月4日\",\"excerpt\":\"<h1> 11.容器视图</h1>\\n<p>容器视图是 SwiftUI 中的一个重要组成部分，它们用于组合和管理其他视图，从而创建出复杂的用户界面。</p>\\n<h2> 常见的容器视图</h2>\\n<p>SwiftUI 中有很多种容器视图，每种容器视图都有不同的用途和特点。下面是一些常见的容器视图：</p>\\n<h3> VStack 和 HStack</h3>\\n<p>VStack 和 HStack 都用于将多个视图按垂直或水平方向排列。VStack 将视图从上到下排列，而 HStack 将视图从左到右排列。这两种容器视图都支持对子视图的对齐方式、间距、填充等样式的设置。</p>\\n<h3> ZStack</h3>\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
