export const data = JSON.parse("{\"key\":\"v-1b4ed985\",\"path\":\"/%E5%BD%92%E6%A1%A3/SwiftUI/13.html\",\"title\":\"13.列表视图\",\"lang\":\"zh-CN\",\"frontmatter\":{\"date\":\"2022-01-04T00:00:00.000Z\",\"category\":[\"苹果\",\"水果\"],\"tag\":[\"红\",\"大\",\"圆\"],\"description\":\"13.列表视图 在 SwiftUI 中，列表视图是一个非常重要的组件，可以用于显示数据列表、菜单、选项卡等。 SwiftUI 中的列表视图，包括 List 和 ForEach 两个组件的基本用法和高级用法。我们将通过一个示例来演示如何使用列表视图显示数据列表，并在列表项中添加图像、文本和交互控件。 List 组件 List 组件是 SwiftUI 中的列表视图，可以用于显示数据列表。List 组件需要一个数据源和一个内容视图，其中数据源用于提供列表数据，内容视图用于定义列表项的布局和样式。例如，我们可以使用 List 组件来显示一个简单的字符串数组：\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"http://yunpu.tech/%E5%BD%92%E6%A1%A3/SwiftUI/13.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"夏日的瓜牛\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"13.列表视图\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"13.列表视图 在 SwiftUI 中，列表视图是一个非常重要的组件，可以用于显示数据列表、菜单、选项卡等。 SwiftUI 中的列表视图，包括 List 和 ForEach 两个组件的基本用法和高级用法。我们将通过一个示例来演示如何使用列表视图显示数据列表，并在列表项中添加图像、文本和交互控件。 List 组件 List 组件是 SwiftUI 中的列表视图，可以用于显示数据列表。List 组件需要一个数据源和一个内容视图，其中数据源用于提供列表数据，内容视图用于定义列表项的布局和样式。例如，我们可以使用 List 组件来显示一个简单的字符串数组：\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"红\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"大\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"圆\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2022-01-04T00:00:00.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"13.列表视图\\\",\\\"image\\\":[\\\"\\\"],\\\"datePublished\\\":\\\"2022-01-04T00:00:00.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[]}\"]]},\"headers\":[{\"level\":2,\"title\":\"List 组件\",\"slug\":\"list-组件\",\"link\":\"#list-组件\",\"children\":[]},{\"level\":2,\"title\":\"ForEach 组件\",\"slug\":\"foreach-组件\",\"link\":\"#foreach-组件\",\"children\":[]},{\"level\":2,\"title\":\"列表视图的高级用法\",\"slug\":\"列表视图的高级用法\",\"link\":\"#列表视图的高级用法\",\"children\":[{\"level\":3,\"title\":\"滚动到指定位置\",\"slug\":\"滚动到指定位置\",\"link\":\"#滚动到指定位置\",\"children\":[]},{\"level\":3,\"title\":\"滑动删除\",\"slug\":\"滑动删除\",\"link\":\"#滑动删除\",\"children\":[]},{\"level\":3,\"title\":\"拖放排序\",\"slug\":\"拖放排序\",\"link\":\"#拖放排序\",\"children\":[]}]},{\"level\":2,\"title\":\"总结\",\"slug\":\"总结\",\"link\":\"#总结\",\"children\":[]}],\"readingTime\":{\"minutes\":4.72,\"words\":1415},\"filePathRelative\":\"归档/SwiftUI/13.md\",\"localizedDate\":\"2022年1月4日\",\"excerpt\":\"<h1> 13.列表视图</h1>\\n<p>在 SwiftUI 中，列表视图是一个非常重要的组件，可以用于显示数据列表、菜单、选项卡等。<br></p>\\n<p>SwiftUI 中的列表视图，包括 List 和 ForEach 两个组件的基本用法和高级用法。我们将通过一个示例来演示如何使用列表视图显示数据列表，并在列表项中添加图像、文本和交互控件。</p>\\n<h2> List 组件</h2>\\n<p>List 组件是 SwiftUI 中的列表视图，可以用于显示数据列表。List 组件需要一个数据源和一个内容视图，其中数据源用于提供列表数据，内容视图用于定义列表项的布局和样式。例如，我们可以使用 List 组件来显示一个简单的字符串数组：</p>\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
