<template><div><h1 id="类型推断" tabindex="-1"><a class="header-anchor" href="#类型推断" aria-hidden="true">#</a> 类型推断</h1>
<p>Swift是一种静态类型语言，这意味着声明的每个属性、常量和变量的类型都需要在编译时指定。然而，这通常不是需要手动完成的事情，相反，编译器能够自行计算出广泛的类型信息——这要归功于Swift支持类型推断。</p>
<p>这里声明了一些常量——所有这些都没有指定任何类型，因为编译器能够根据分配的值推断该信息：</p>
<div class="language-swift line-numbers-mode" data-ext="swift"><pre v-pre class="language-swift"><code><span class="token keyword">let</span> number <span class="token operator">=</span> <span class="token number">42</span>
<span class="token keyword">let</span> string <span class="token operator">=</span> <span class="token string-literal"><span class="token string">"Hello, world!"</span></span>
<span class="token keyword">let</span> array <span class="token operator">=</span> <span class="token punctuation">[</span><span class="token number">1</span><span class="token punctuation">,</span> <span class="token number">1</span><span class="token punctuation">,</span> <span class="token number">2</span><span class="token punctuation">,</span> <span class="token number">3</span><span class="token punctuation">,</span> <span class="token number">5</span><span class="token punctuation">,</span> <span class="token number">8</span><span class="token punctuation">]</span>
<span class="token keyword">let</span> dictionary <span class="token operator">=</span> <span class="token punctuation">[</span><span class="token string-literal"><span class="token string">"key"</span></span><span class="token punctuation">:</span> <span class="token string-literal"><span class="token string">"value"</span></span><span class="token punctuation">]</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>作为比较，如果手动指定每个常量的类型，上述分配会是什么样子：</p>
<div class="language-swift line-numbers-mode" data-ext="swift"><pre v-pre class="language-swift"><code><span class="token keyword">let</span> number<span class="token punctuation">:</span> <span class="token class-name">Int</span> <span class="token operator">=</span> <span class="token number">42</span>
<span class="token keyword">let</span> string<span class="token punctuation">:</span> <span class="token class-name">String</span> <span class="token operator">=</span> <span class="token string-literal"><span class="token string">"Hello, world!"</span></span>
<span class="token keyword">let</span> array<span class="token punctuation">:</span> <span class="token punctuation">[</span><span class="token class-name">Int</span><span class="token punctuation">]</span> <span class="token operator">=</span> <span class="token punctuation">[</span><span class="token number">1</span><span class="token punctuation">,</span> <span class="token number">1</span><span class="token punctuation">,</span> <span class="token number">2</span><span class="token punctuation">,</span> <span class="token number">3</span><span class="token punctuation">,</span> <span class="token number">5</span><span class="token punctuation">,</span> <span class="token number">8</span><span class="token punctuation">]</span>
<span class="token keyword">let</span> dictionary<span class="token punctuation">:</span> <span class="token punctuation">[</span><span class="token class-name">String</span><span class="token punctuation">:</span> <span class="token class-name">String</span><span class="token punctuation">]</span> <span class="token operator">=</span> <span class="token punctuation">[</span><span class="token string-literal"><span class="token string">"key"</span></span><span class="token punctuation">:</span> <span class="token string-literal"><span class="token string">"value"</span></span><span class="token punctuation">]</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>因此，类型推理在使Swift的语法尽可能轻量级方面发挥着重要作用，不仅在变量声明和其他类型的赋值时，而且在许多其他类型的情况下也是如此。
例如，在这里我们定义了一个描述各种联系人的枚举，以及一个允许加载属于特定类型的Contact值数组的函数：</p>
<div class="language-swift line-numbers-mode" data-ext="swift"><pre v-pre class="language-swift"><code><span class="token keyword">enum</span> <span class="token class-name">ContactKind</span> <span class="token punctuation">{</span>
    <span class="token keyword">case</span> family
    <span class="token keyword">case</span> friend
    <span class="token keyword">case</span> coworker
    <span class="token keyword">case</span> acquaintance
<span class="token punctuation">}</span>

<span class="token keyword">func</span> <span class="token function-definition function">loadContacts</span><span class="token punctuation">(</span>ofKind kind<span class="token punctuation">:</span> <span class="token class-name">ContactKind</span><span class="token punctuation">)</span> <span class="token operator">-></span> <span class="token punctuation">[</span><span class="token class-name">Contact</span><span class="token punctuation">]</span> <span class="token punctuation">{</span>
    <span class="token operator">...</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>虽然我们通常通过指定类型和大小写（如ContactKind.friend）来引用上述枚举的成员，但由于类型推断，在已知的类型上下文中引用大小写时，我们可以完全省略类型名称——例如在调用上述函数时：</p>
<div class="language-swift line-numbers-mode" data-ext="swift"><pre v-pre class="language-swift"><code><span class="token keyword">let</span> friends <span class="token operator">=</span> <span class="token function">loadContacts</span><span class="token punctuation">(</span>ofKind<span class="token punctuation">:</span> <span class="token punctuation">.</span>friend<span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>上述“点语法”不只适用于枚举情况，在引用任何静态属性或方法时也有效。
例如，在这里，我们用一个静态属性扩展了Foundation的URL类型，该属性创建了一个指向这个网站的URL：</p>
<div class="language-swift line-numbers-mode" data-ext="swift"><pre v-pre class="language-swift"><code><span class="token keyword">extension</span> <span class="token constant">URL</span> <span class="token punctuation">{</span>
    <span class="token keyword">static</span> <span class="token keyword">var</span> googleUrl<span class="token punctuation">:</span> <span class="token constant">URL</span> <span class="token punctuation">{</span>
        <span class="token function">URL</span><span class="token punctuation">(</span>string<span class="token punctuation">:</span> <span class="token string-literal"><span class="token string">"https://google.com"</span></span><span class="token punctuation">)</span><span class="token operator">!</span>
    <span class="token punctuation">}</span>
<span class="token punctuation">}</span>

<span class="token keyword">let</span> publisher <span class="token operator">=</span> <span class="token class-name">URLSession</span><span class="token punctuation">.</span>shared<span class="token punctuation">.</span><span class="token function">dataTaskPublisher</span><span class="token punctuation">(</span><span class="token keyword">for</span><span class="token punctuation">:</span> <span class="token punctuation">.</span>swiftBySundell<span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>当数字文字分配给变量或常量时，默认情况下，可以推断为具有Int类型——这是一个完全合理的默认值——但如果我们希望使用另一种数字类型，如Double或Float，我们需要手动指定这些类型。以下是一些做到这一点的方法：</p>
<div class="language-swift line-numbers-mode" data-ext="swift"><pre v-pre class="language-swift"><code><span class="token keyword">let</span> int <span class="token operator">=</span> <span class="token number">42</span>
<span class="token keyword">let</span> double <span class="token operator">=</span> <span class="token number">42</span> <span class="token keyword">as</span> <span class="token class-name">Double</span>
<span class="token keyword">let</span> float<span class="token punctuation">:</span> <span class="token class-name">Float</span> <span class="token operator">=</span> <span class="token number">42</span>
<span class="token keyword">let</span> cgFloat <span class="token operator">=</span> <span class="token class-name">CGFloat</span><span class="token punctuation">(</span><span class="token number">42</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>另一种需要向编译器提供一些额外类型信息的是调用具有通用返回类型的函数时：
在这里，我们用一种通用方法扩展了内置的Bundle类型，该方法允许我们轻松加载和解码在应用程序中捆绑的任何JSON文件：</p>
<div class="language-swift line-numbers-mode" data-ext="swift"><pre v-pre class="language-swift"><code><span class="token keyword">extension</span> <span class="token class-name">Bundle</span> <span class="token punctuation">{</span>
    <span class="token keyword">struct</span> <span class="token class-name">MissingFileError</span><span class="token punctuation">:</span> <span class="token class-name">Error</span> <span class="token punctuation">{</span>
        <span class="token keyword">var</span> name<span class="token punctuation">:</span> <span class="token class-name">String</span>
    <span class="token punctuation">}</span>

    <span class="token keyword">func</span> <span class="token function-definition function">decodeJSONFile</span><span class="token operator">&lt;</span><span class="token class-name">T</span><span class="token punctuation">:</span> <span class="token class-name">Decodable</span><span class="token operator">></span><span class="token punctuation">(</span>named name<span class="token punctuation">:</span> <span class="token class-name">String</span><span class="token punctuation">)</span> <span class="token keyword">throws</span> <span class="token operator">-></span> <span class="token class-name">T</span> <span class="token punctuation">{</span>
        <span class="token keyword">guard</span> <span class="token keyword">let</span> url <span class="token operator">=</span> <span class="token keyword">self</span><span class="token punctuation">.</span><span class="token function">url</span><span class="token punctuation">(</span>forResource<span class="token punctuation">:</span> name<span class="token punctuation">,</span> withExtension<span class="token punctuation">:</span> <span class="token string-literal"><span class="token string">"json"</span></span><span class="token punctuation">)</span> <span class="token keyword">else</span> <span class="token punctuation">{</span>
            <span class="token keyword">throw</span> <span class="token class-name">MissingFileError</span><span class="token punctuation">(</span>name<span class="token punctuation">:</span> name<span class="token punctuation">)</span>
        <span class="token punctuation">}</span>

        <span class="token keyword">let</span> data <span class="token operator">=</span> <span class="token keyword">try</span> <span class="token class-name">Data</span><span class="token punctuation">(</span>contentsOf<span class="token punctuation">:</span> url<span class="token punctuation">)</span>
        <span class="token keyword">let</span> decoder <span class="token operator">=</span> <span class="token class-name">JSONDecoder</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
        <span class="token keyword">return</span> <span class="token keyword">try</span> decoder<span class="token punctuation">.</span><span class="token function">decode</span><span class="token punctuation">(</span><span class="token class-name">T</span><span class="token punctuation">.</span><span class="token keyword">self</span><span class="token punctuation">,</span> from<span class="token punctuation">:</span> data<span class="token punctuation">)</span>
    <span class="token punctuation">}</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>现在，假设在应用程序开发过程中，在真正的服务器和网络代码启动并运行之前，我们希望从捆绑的JSON文件中解码以下User类型的实例：</p>
<div class="language-swift line-numbers-mode" data-ext="swift"><pre v-pre class="language-swift"><code><span class="token keyword">struct</span> <span class="token class-name">User</span><span class="token punctuation">:</span> <span class="token class-name">Codable</span> <span class="token punctuation">{</span>
    <span class="token keyword">var</span> name<span class="token punctuation">:</span> <span class="token class-name">String</span>
    <span class="token keyword">var</span> email<span class="token punctuation">:</span> <span class="token class-name">String</span>
    <span class="token keyword">var</span> lastLoginDate<span class="token punctuation">:</span> <span class="token class-name">Date</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>然而，如果像这样调用decodeJSONFile方法，最终会出现编译器错误：</p>
<div class="language-swift line-numbers-mode" data-ext="swift"><pre v-pre class="language-swift"><code><span class="token comment">// Error: Generic parameter 'T' could not be inferred</span>
<span class="token keyword">let</span> user <span class="token operator">=</span> <span class="token keyword">try</span> <span class="token class-name">Bundle</span><span class="token punctuation">.</span>main<span class="token punctuation">.</span><span class="token function">decodeJSONFile</span><span class="token punctuation">(</span>named<span class="token punctuation">:</span> <span class="token string-literal"><span class="token string">"user-mock"</span></span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><p>这是因为将解码任何给定JSON文件的确切类型取决于通用类型T在每个调用站点的实际引用什么——由于没有向编译器提供上述任何此类信息，最终会出现错误。在这种情况下，编译器根本无法知道希望解码User实例。
为了解决这个问题，可以使用与上面相同的技术来指定不同类型的数值，并给user常量一个显式类型，或者使用关键字：</p>
<div class="language-swift line-numbers-mode" data-ext="swift"><pre v-pre class="language-swift"><code><span class="token keyword">let</span> user<span class="token punctuation">:</span> <span class="token class-name">User</span> <span class="token operator">=</span> <span class="token keyword">try</span> <span class="token class-name">Bundle</span><span class="token punctuation">.</span>main<span class="token punctuation">.</span><span class="token function">decodeJSONFile</span><span class="token punctuation">(</span>named<span class="token punctuation">:</span> <span class="token string-literal"><span class="token string">"user-mock"</span></span><span class="token punctuation">)</span>
<span class="token keyword">let</span> user <span class="token operator">=</span> <span class="token keyword">try</span> <span class="token class-name">Bundle</span><span class="token punctuation">.</span>main<span class="token punctuation">.</span><span class="token function">decodeJSONFile</span><span class="token punctuation">(</span>named<span class="token punctuation">:</span> <span class="token string-literal"><span class="token string">"user-mock"</span></span><span class="token punctuation">)</span> <span class="token keyword">as</span> <span class="token class-name">User</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><p>然而，如果在已知所需的返回类型的情况下调用decodeJSONFile方法，那么可以再次让Swift的类型推理机制为找出该信息——就像在这种情况下定义了一个名为MockData的包装器结构，该结构具有User类型属性，将结果分配给：</p>
<div class="language-swift line-numbers-mode" data-ext="swift"><pre v-pre class="language-swift"><code><span class="token keyword">struct</span> <span class="token class-name">MockData</span> <span class="token punctuation">{</span>
    <span class="token keyword">var</span> user<span class="token punctuation">:</span> <span class="token class-name">User</span>
<span class="token punctuation">}</span>

<span class="token keyword">let</span> mockData <span class="token operator">=</span> <span class="token keyword">try</span> <span class="token class-name">MockData</span><span class="token punctuation">(</span>
    user<span class="token punctuation">:</span> <span class="token class-name">Bundle</span><span class="token punctuation">.</span>main<span class="token punctuation">.</span><span class="token function">decodeJSONFile</span><span class="token punctuation">(</span>named<span class="token punctuation">:</span> <span class="token string-literal"><span class="token string">"user-mock"</span></span><span class="token punctuation">)</span>
<span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>类型推断确实有与之相关的计算成本，这完全发生在编译时，因此它不会影响我们应用程序的运行时性能。然而，如果我们确实遇到一个表达式编译器需要很长时间才能弄清楚，那么总是可以使用上述技术之一来手动指定这些类型。</p>
</div></template>


