export const data = JSON.parse("{\"key\":\"v-a8029926\",\"path\":\"/%E5%BC%80%E5%8F%91/%E3%80%8E-iOS%E3%80%8F/23.html\",\"title\":\"isMemberOfClass 、 isKindOfClass和 isSubclassOfClass\",\"lang\":\"zh-CN\",\"frontmatter\":{\"date\":\"2022-01-12T00:00:00.000Z\",\"category\":[\"蔬菜\"],\"tag\":[\"红\",\"圆\"],\"star\":true,\"sticky\":true,\"description\":\"isMemberOfClass 、 isKindOfClass和 isSubclassOfClass isMemberOfClass, isKindOfClass, 和 isSubclassOfClass 是 Objective-C 和 Swift 中用于检查对象类型的方法。 这三个方法都是用来判断一个对象的类型，即判断一个对象是否是某个类或其子类的实例。 isMemberOfClass 用于检查对象是否是指定类的实例，不包括子类。如果该对象是指定类的实例，则返回 YES，否则返回 NO。 isKindOfClass 用于检查对象是否是指定类或其子类的实例。如果该对象是指定类或其子类的实例，则返回 YES，否则返回 NO。 isSubclassOfClass 用于检查一个类是否是另一个类的子类。如果该类是另一个类的子类，则返回 YES，否则返回 NO。\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"http://yunpu.tech/%E5%BC%80%E5%8F%91/%E3%80%8E-iOS%E3%80%8F/23.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"夏日的瓜牛\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"isMemberOfClass 、 isKindOfClass和 isSubclassOfClass\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"isMemberOfClass 、 isKindOfClass和 isSubclassOfClass isMemberOfClass, isKindOfClass, 和 isSubclassOfClass 是 Objective-C 和 Swift 中用于检查对象类型的方法。 这三个方法都是用来判断一个对象的类型，即判断一个对象是否是某个类或其子类的实例。 isMemberOfClass 用于检查对象是否是指定类的实例，不包括子类。如果该对象是指定类的实例，则返回 YES，否则返回 NO。 isKindOfClass 用于检查对象是否是指定类或其子类的实例。如果该对象是指定类或其子类的实例，则返回 YES，否则返回 NO。 isSubclassOfClass 用于检查一个类是否是另一个类的子类。如果该类是另一个类的子类，则返回 YES，否则返回 NO。\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"红\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"圆\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2022-01-12T00:00:00.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"isMemberOfClass 、 isKindOfClass和 isSubclassOfClass\\\",\\\"image\\\":[\\\"\\\"],\\\"datePublished\\\":\\\"2022-01-12T00:00:00.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[]}\"]]},\"headers\":[],\"readingTime\":{\"minutes\":0.83,\"words\":249},\"filePathRelative\":\"开发/『-iOS』/23.md\",\"localizedDate\":\"2022年1月12日\",\"excerpt\":\"<h1> isMemberOfClass 、 isKindOfClass和 isSubclassOfClass</h1>\\n<p>isMemberOfClass, isKindOfClass, 和 isSubclassOfClass 是 Objective-C 和 Swift 中用于检查对象类型的方法。<br></p>\\n<p>这三个方法都是用来判断一个对象的类型，即判断一个对象是否是某个类或其子类的实例。</p>\\n<ul>\\n<li>isMemberOfClass 用于检查对象是否是指定类的实例，不包括子类。如果该对象是指定类的实例，则返回 YES，否则返回 NO。</li>\\n<li>isKindOfClass 用于检查对象是否是指定类或其子类的实例。如果该对象是指定类或其子类的实例，则返回 YES，否则返回 NO。</li>\\n<li>isSubclassOfClass 用于检查一个类是否是另一个类的子类。如果该类是另一个类的子类，则返回 YES，否则返回 NO。</li>\\n</ul>\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
