export const data = JSON.parse("{\"key\":\"v-9a5bd42e\",\"path\":\"/%E5%BC%80%E5%8F%91/%E3%80%8E-iOS%E3%80%8F/27.html\",\"title\":\"HTTPS加密原理\",\"lang\":\"zh-CN\",\"frontmatter\":{\"date\":\"2022-01-12T00:00:00.000Z\",\"category\":[\"蔬菜\"],\"tag\":[\"红\",\"圆\"],\"star\":true,\"sticky\":true,\"description\":\"HTTPS加密原理 HTTPS（Hyper Text Transfer Protocol over Secure Socket Layer）是在HTTP的基础上加入了SSL/TLS协议来实现数据加密和身份认证的安全网络协议。HTTPS协议在iOS开发中被广泛应用。在移动应用中，保护用户的隐私和安全至关重要。其中，HTTPS是一种用于保护网络通信安全的加密协议。在iOS中，使用HTTPS来保护应用的网络通信是非常重要的。 HTTPS加密原理 HTTPS协议主要通过SSL/TLS协议实现加密通信和身份认证。SSL（Secure Sockets Layer）是一个基于非对称密钥加密和对称密钥加密结合的协议，TLS（Transport Layer Security）则是SSL的升级版，是目前互联网上使用最广泛的安全协议。\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"http://yunpu.tech/%E5%BC%80%E5%8F%91/%E3%80%8E-iOS%E3%80%8F/27.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"夏日的瓜牛\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"HTTPS加密原理\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"HTTPS加密原理 HTTPS（Hyper Text Transfer Protocol over Secure Socket Layer）是在HTTP的基础上加入了SSL/TLS协议来实现数据加密和身份认证的安全网络协议。HTTPS协议在iOS开发中被广泛应用。在移动应用中，保护用户的隐私和安全至关重要。其中，HTTPS是一种用于保护网络通信安全的加密协议。在iOS中，使用HTTPS来保护应用的网络通信是非常重要的。 HTTPS加密原理 HTTPS协议主要通过SSL/TLS协议实现加密通信和身份认证。SSL（Secure Sockets Layer）是一个基于非对称密钥加密和对称密钥加密结合的协议，TLS（Transport Layer Security）则是SSL的升级版，是目前互联网上使用最广泛的安全协议。\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"红\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"圆\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2022-01-12T00:00:00.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"HTTPS加密原理\\\",\\\"image\\\":[\\\"\\\"],\\\"datePublished\\\":\\\"2022-01-12T00:00:00.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[]}\"]]},\"headers\":[{\"level\":2,\"title\":\"HTTPS加密原理\",\"slug\":\"https加密原理-1\",\"link\":\"#https加密原理-1\",\"children\":[]},{\"level\":2,\"title\":\"SSL/TLS协议的基本流程\",\"slug\":\"ssl-tls协议的基本流程\",\"link\":\"#ssl-tls协议的基本流程\",\"children\":[]},{\"level\":2,\"title\":\"数字证书的作用\",\"slug\":\"数字证书的作用\",\"link\":\"#数字证书的作用\",\"children\":[]},{\"level\":2,\"title\":\"常见的HTTPS攻击方式\",\"slug\":\"常见的https攻击方式\",\"link\":\"#常见的https攻击方式\",\"children\":[]}],\"readingTime\":{\"minutes\":4.96,\"words\":1488},\"filePathRelative\":\"开发/『-iOS』/27.md\",\"localizedDate\":\"2022年1月12日\",\"excerpt\":\"<h1> HTTPS加密原理</h1>\\n<p>HTTPS（Hyper Text Transfer Protocol over Secure Socket Layer）是在HTTP的基础上加入了SSL/TLS协议来实现数据加密和身份认证的安全网络协议。HTTPS协议在iOS开发中被广泛应用。在移动应用中，保护用户的隐私和安全至关重要。其中，HTTPS是一种用于保护网络通信安全的加密协议。在iOS中，使用HTTPS来保护应用的网络通信是非常重要的。</p>\\n<h2> HTTPS加密原理</h2>\\n<p>HTTPS协议主要通过SSL/TLS协议实现加密通信和身份认证。SSL（Secure Sockets Layer）是一个基于非对称密钥加密和对称密钥加密结合的协议，TLS（Transport Layer Security）则是SSL的升级版，是目前互联网上使用最广泛的安全协议。<br></p>\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
