export const data = JSON.parse("{\"key\":\"v-0d551c36\",\"path\":\"/%E5%BC%80%E5%8F%91/%E3%80%8EiOS%E3%80%8F/17.html\",\"title\":\"Block种类\",\"lang\":\"zh-CN\",\"frontmatter\":{\"date\":\"2020-5-09\",\"category\":[\"iOS\"],\"tag\":[\"Block\"],\"description\":\"Block种类 在 Objective-C 中，Block 是一种带有自动捕获变量的匿名函数。Block 可以在定义时捕获其外部作用域中的变量，并将这些变量保存在 Block 结构体中。当调用 Block 时，它会从结构体中获取这些变量，并执行函数体中的代码。Block 的定义形式如下： ^return_type (arguments) { // code }\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"http://yunpu.tech/%E5%BC%80%E5%8F%91/%E3%80%8EiOS%E3%80%8F/17.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"夏日的瓜牛\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"Block种类\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"Block种类 在 Objective-C 中，Block 是一种带有自动捕获变量的匿名函数。Block 可以在定义时捕获其外部作用域中的变量，并将这些变量保存在 Block 结构体中。当调用 Block 时，它会从结构体中获取这些变量，并执行函数体中的代码。Block 的定义形式如下： ^return_type (arguments) { // code }\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"Block\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2020-05-08T16:00:00.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"Block种类\\\",\\\"image\\\":[\\\"\\\"],\\\"datePublished\\\":\\\"2020-05-08T16:00:00.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[]}\"]]},\"headers\":[{\"level\":2,\"title\":\"NSStackBlock\",\"slug\":\"nsstackblock\",\"link\":\"#nsstackblock\",\"children\":[]},{\"level\":2,\"title\":\"NSMallocBlock\",\"slug\":\"nsmallocblock\",\"link\":\"#nsmallocblock\",\"children\":[]},{\"level\":2,\"title\":\"NSGlobalBlock\",\"slug\":\"nsglobalblock\",\"link\":\"#nsglobalblock\",\"children\":[]}],\"readingTime\":{\"minutes\":2.66,\"words\":799},\"filePathRelative\":\"开发/『iOS』/17.md\",\"localizedDate\":\"2020年5月9日\",\"excerpt\":\"<h1> Block种类</h1>\\n<p>在 Objective-C 中，Block 是一种带有自动捕获变量的匿名函数。Block 可以在定义时捕获其外部作用域中的变量，并将这些变量保存在 Block 结构体中。当调用 Block 时，它会从结构体中获取这些变量，并执行函数体中的代码。Block 的定义形式如下：</p>\\n<div class=\\\"language-objective line-numbers-mode\\\" data-ext=\\\"objective\\\"><pre class=\\\"language-objective\\\"><code>^return_type (arguments) {\\n    // code\\n}\\n</code></pre><div class=\\\"line-numbers\\\" aria-hidden=\\\"true\\\"><div class=\\\"line-number\\\"></div><div class=\\\"line-number\\\"></div><div class=\\\"line-number\\\"></div></div></div>\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
