export const data = JSON.parse("{\"key\":\"v-1f337f7a\",\"path\":\"/%E5%BD%92%E6%A1%A3/SwiftUI%E7%AC%94%E8%AE%B0/10.html\",\"title\":\"10.手势\",\"lang\":\"zh-CN\",\"frontmatter\":{\"date\":\"2022-01-04T00:00:00.000Z\",\"category\":[\"苹果\",\"水果\"],\"tag\":[\"红\",\"大\",\"圆\"],\"description\":\"10.手势 在SwiftUI中，可以通过手势识别器（Gesture Recognizers）来捕捉和响应用户的手势操作。SwiftUI提供了一些内置的手势识别器，例如拖动手势、轻击手势、长按手势等，同时也支持自定义手势识别器。 内置手势识别器 SwiftUI提供了多种内置手势识别器，可以通过视图修饰符.gesture()来添加手势识别器。常见的内置手势识别器有： TapGesture：轻击手势，可以设置点击次数、手指数等属性。 LongPressGesture：长按手势，可以设置最短持续时间、最大移动距离等属性。 DragGesture：拖动手势，可以设置最大/最小拖动速度、拖动方向等属性。 MagnificationGesture：放大/缩小手势，可以设置最小/最大放大比例等属性。 RotationGesture：旋转手势，可以设置最小/最大旋转角度等属性。\"},\"headers\":[{\"level\":2,\"title\":\"内置手势识别器\",\"slug\":\"内置手势识别器\",\"link\":\"#内置手势识别器\",\"children\":[{\"level\":3,\"title\":\"TapGesture\",\"slug\":\"tapgesture\",\"link\":\"#tapgesture\",\"children\":[]},{\"level\":3,\"title\":\"LongPressGesture\",\"slug\":\"longpressgesture\",\"link\":\"#longpressgesture\",\"children\":[]},{\"level\":3,\"title\":\"DragGesture\",\"slug\":\"draggesture\",\"link\":\"#draggesture\",\"children\":[]},{\"level\":3,\"title\":\"MagnificationGesture\",\"slug\":\"magnificationgesture\",\"link\":\"#magnificationgesture\",\"children\":[]},{\"level\":3,\"title\":\"RotationGesture\",\"slug\":\"rotationgesture\",\"link\":\"#rotationgesture\",\"children\":[]}]},{\"level\":2,\"title\":\"自定义手势识别器\",\"slug\":\"自定义手势识别器\",\"link\":\"#自定义手势识别器\",\"children\":[]},{\"level\":2,\"title\":\"simultaneousGesture\",\"slug\":\"simultaneousgesture\",\"link\":\"#simultaneousgesture\",\"children\":[]},{\"level\":2,\"title\":\"sequenced\",\"slug\":\"sequenced\",\"link\":\"#sequenced\",\"children\":[]},{\"level\":2,\"title\":\"exclusiveGesture\",\"slug\":\"exclusivegesture\",\"link\":\"#exclusivegesture\",\"children\":[]},{\"level\":2,\"title\":\"交互动画\",\"slug\":\"交互动画\",\"link\":\"#交互动画\",\"children\":[{\"level\":3,\"title\":\"点击缩放\",\"slug\":\"点击缩放\",\"link\":\"#点击缩放\",\"children\":[]},{\"level\":3,\"title\":\"拖拽移动\",\"slug\":\"拖拽移动\",\"link\":\"#拖拽移动\",\"children\":[]}]}],\"readingTime\":{\"minutes\":6.2,\"words\":1861},\"filePathRelative\":\"归档/SwiftUI笔记/10.md\",\"localizedDate\":\"2022年1月4日\",\"excerpt\":\"<h1> 10.手势</h1>\\n<p>在SwiftUI中，可以通过手势识别器（Gesture Recognizers）来捕捉和响应用户的手势操作。SwiftUI提供了一些内置的手势识别器，例如拖动手势、轻击手势、长按手势等，同时也支持自定义手势识别器。</p>\\n<h2> 内置手势识别器</h2>\\n<p>SwiftUI提供了多种内置手势识别器，可以通过视图修饰符.gesture()来添加手势识别器。常见的内置手势识别器有：</p>\\n<ul>\\n<li>TapGesture：轻击手势，可以设置点击次数、手指数等属性。</li>\\n<li>LongPressGesture：长按手势，可以设置最短持续时间、最大移动距离等属性。</li>\\n<li>DragGesture：拖动手势，可以设置最大/最小拖动速度、拖动方向等属性。</li>\\n<li>MagnificationGesture：放大/缩小手势，可以设置最小/最大放大比例等属性。</li>\\n<li>RotationGesture：旋转手势，可以设置最小/最大旋转角度等属性。</li>\\n</ul>\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
