export const data = JSON.parse("{\"key\":\"v-007aac23\",\"path\":\"/%E5%BC%80%E5%8F%91/Swift/5.html\",\"title\":\"as，as?，as!\",\"lang\":\"zh-CN\",\"frontmatter\":{\"date\":\"2023-01-03T00:00:00.000Z\",\"category\":[\"苹果\",\"水果\"],\"tag\":[\"红\",\"大\",\"圆\"],\"description\":\"as，as?，as! 下面第二行代码具有运行时错误： 8 as Double // fine 8 as! Double // crashes\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"http://yunpu.tech/%E5%BC%80%E5%8F%91/Swift/5.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"夏日的瓜牛\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"as，as?，as!\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"as，as?，as! 下面第二行代码具有运行时错误： 8 as Double // fine 8 as! Double // crashes\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"红\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"大\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"圆\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2023-01-03T00:00:00.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"as，as?，as!\\\",\\\"image\\\":[\\\"\\\"],\\\"datePublished\\\":\\\"2023-01-03T00:00:00.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[]}\"]]},\"headers\":[{\"level\":2,\"title\":\"as?和as!是运行时操作\",\"slug\":\"as-和as-是运行时操作\",\"link\":\"#as-和as-是运行时操作\",\"children\":[]},{\"level\":2,\"title\":\"as编译时执行类型强制\",\"slug\":\"as编译时执行类型强制\",\"link\":\"#as编译时执行类型强制\",\"children\":[]},{\"level\":2,\"title\":\"在模式匹配中，as运行时操作一样\",\"slug\":\"在模式匹配中-as运行时操作一样\",\"link\":\"#在模式匹配中-as运行时操作一样\",\"children\":[]},{\"level\":2,\"title\":\"对比举例\",\"slug\":\"对比举例\",\"link\":\"#对比举例\",\"children\":[]}],\"readingTime\":{\"minutes\":2.24,\"words\":672},\"filePathRelative\":\"开发/Swift/5.md\",\"localizedDate\":\"2023年1月3日\",\"excerpt\":\"<h1> as，as?，as!</h1>\\n<p>下面第二行代码具有运行时错误：</p>\\n<div class=\\\"language-swift line-numbers-mode\\\" data-ext=\\\"swift\\\"><pre class=\\\"language-swift\\\"><code><span class=\\\"token number\\\">8</span> <span class=\\\"token keyword\\\">as</span> <span class=\\\"token class-name\\\">Double</span> <span class=\\\"token comment\\\">// fine</span>\\n<span class=\\\"token number\\\">8</span> <span class=\\\"token keyword\\\">as</span><span class=\\\"token operator\\\">!</span> <span class=\\\"token class-name\\\">Double</span> <span class=\\\"token comment\\\">// crashes</span>\\n</code></pre><div class=\\\"line-numbers\\\" aria-hidden=\\\"true\\\"><div class=\\\"line-number\\\"></div><div class=\\\"line-number\\\"></div></div></div>\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
